# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-31 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tour_Name', models.CharField(max_length=150)),
                ('Your_Name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100)),
                ('Mobile_Number', models.CharField(max_length=50)),
                ('Number_Of_Travellers', models.IntegerField(null=True)),
                ('message', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='MakeMyOwnTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Your_Full_Name', models.CharField(max_length=150)),
                ('Your_Email', models.CharField(max_length=150)),
                ('Your_Mobile_Number', models.CharField(max_length=100)),
                ('Number_Of_Travellers', models.IntegerField(null=True)),
                ('Departure_City', models.CharField(choices=[('KH', 'Karachi'), ('ISL', 'Islamabad'), ('LH', 'Lahore')], max_length=100)),
                ('Date', models.DateField()),
                ('Trip_Duration', models.IntegerField(null=True)),
                ('Enter_Locations', models.CharField(max_length=500)),
                ('preferences', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('picture', models.ImageField(upload_to=b'')),
                ('price', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('date', models.DateField()),
                ('days', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('departure', models.CharField(max_length=100)),
                ('departureTime', models.TimeField()),
                ('returnTime', models.TimeField()),
                ('included', models.CharField(max_length=300)),
                ('notIncluded', models.CharField(default='', max_length=300)),
                ('itinerary', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('picture', models.ImageField(upload_to=b'')),
                ('description', models.CharField(max_length=400)),
            ],
        ),
    ]
