# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-01 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='itinerary',
        ),
    ]
